env:
  commonjs: true
  es6: true
  node: true
  mocha: true
extends: 
  - 'eslint:recommended'
  - 'plugin:mocha/recommended'
plugins:
  - mocha
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
